name: createPR

on:
  workflow_dispatch:
permissions:
  id-token: write
jobs:
  createPR:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          token: ${{secrets.TOKEN}}
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: ${{ secrets.REGION }}
          role-to-assume: ${{ secrets.ROLE }}
          role-session-name: MySessionName
      - name: setup git config
        run: |
          git config user.name "Actions Bot"
          git config user.email "<>"
      - name: Create Pull Request
        uses: kiryltestorg/praction@v0.8.3
        with:
          token: ${{ secrets.TOKEN }}
          bucketName: ${{ secrets.BUCKETNAME }}
          owner: 'kiryltestorg'
          main_branch: 'main'
          repo: 'mainRepo'
          depPath: ${{ github.workspace }}/Dependencies
          
 
