name: createPR

on:
  workflow_dispatch:
permissions:
  id-token: write
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - dep: "repoA,repoB,repoC"
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: ${{ secrets.REGION }}
          role-to-assume: ${{ secrets.ROLE }}
          role-session-name: MySessionName
      - name: Sync Dependencies
        uses: kiryltestorg/praction@v0.0.7
        with:
          token: ${{ secrets.TOKEN }}
          bucketName: ${{ secrets.BUCKETNAME }}
          path: ${{ secrets.PATH }}
          repo: ${{matrix.dep}}
          depPath: ${{ github.workspace }}/Dependencies
          
      - name: test
        run: echo ${{ matrix.dep }}
