on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: ${{ secrets.REGION }}
          role-to-assume: ${{ secrets.ROLE }}
          role-session-name: MySessionName
      - name: Hello world action step
        id: hello
        uses: kiryl1/testaction@v1.1.3
        with:
          bucketName: ${{ secrets.BUCKETNAME }}
          tarUrl:  ${{ secrets.TARURL }}
          fileName: ${{ secrets.FILENAME }}
          path: ${{ secrets.PATH }}
          
      # Use the output from the `hello` step
      - name: Get the output time
        run: echo "The time was ${{ steps.hello.outputs.time }}"
