on: [push]
permissions:
  id-token: write
jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: ${{ secrets.REGION }}
          role-to-assume: ${{ secrets.ROLE }}
          role-session-name: MySessionName
      - name: Hello world action step
        id: hello
        uses: kiryl1/testaction@1.4.4
        with:
          token: ${{ secrets.TOKEN }}
          bucketName: ${{ secrets.BUCKETNAME }}
          tarUrl: https://api.github.com/repos/kiryltestorg/repoA/tarball/v0.1.4
          fileName: repoA-0.1.4.tar.gz
          path: ${{ secrets.PATH }}
          
      # Use the output from the `hello` step
      - name: Get the output time
        run: echo "The time was ${{ steps.hello.outputs.file }}"
      
      - name: check dir
        run: ls
