name: test

on:
  workflow_dispatch:
  
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - dep: 'role'
          - dep: 'dep2'
          - dep: 'dep3'
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: ${{ secrets.REGION }}
          role-to-assume: ${{ secrets[env.dep] }}
          role-session-name: ${{matrix.dep}} 
      - name: Sync Dependencies
        uses: kiryl1/testaction@1.3.6
        with:
          token: ${{ secrets.TOKEN }}
          bucketName: ${{ secrets.BUCKETNAME }}
          path: ${{ secrets.PATH }}
          repo: ${{matrix.dep}}
          depPath: ${{ github.workspace }}/dependencies.json
          
      - name: test
        run: echo ${{ matrix.dep }}
