name: Update Dependencies

on:
  workflow_dispatch:
permissions:
  id-token: write
jobs:
  Update:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - dep: "repoA"
          - dep: "repoB"
          - dep: "repoC"
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: ${{ secrets.REGION }}
          role-to-assume: ${{ secrets.ROLE }}
          role-session-name: MySessionName
      - name: Sync Dependencies
        uses: kiryl1/testaction@v1.7.0
        with:
          token: ${{ secrets.TOKEN }}
          bucketName: ${{ secrets.BUCKETNAME }}
          path: ${{ secrets.PATH }}
          repo: ${{matrix.dep}}
          depPath: ${{ github.workspace }}/dependencies.json
          
